pipeline {
    agent any
    stages {
        stage('Install Dependencies') {
            steps {
                bat 'pip install pandas'
            }
        }
        stage('Run Analysis') {
            steps {
                bat 'python data_analysis.py'
            }
        }
    }
}
